auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /tmp/loki  # Set a base directory for Loki components

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1  # Set replication factor to 1 for single-instance mode
  chunk_idle_period: 5m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor  # Set a valid working directory

limits_config:
  retention_period: 24h
  allow_structured_metadata: false  # Disable structured metadata
