global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'todo-app'
    static_configs:
      - targets: ['todo-app:2112']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']