{
 "title": "Todo Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total ToDo Added",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"todo.tasks.added_total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Memory Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "heap alloc" }
   ]
  },
  {
   "title": "Handler Latency (p95)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(todo_handler_latency_milliseconds_bucket[15m])) by (le, handler))",
     "legendFormat": "{{handler}} (p95)"
    }
   ]
  },
  {
   "title": "Last 100 Traces (Jaeger)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "limit": 100, "service": "todo-app" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Last 100 Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/logs/todo-app.log\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}